env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
  main: main.go
dockers:
  -
    ids:
      - security-hub-collector
    image_templates:
      - "cmsgov/security-hub-collector:{{ .Tag }}"
    skip_push: true
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "git-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: CMSgov
    name: security-hub-collector
  draft: false
  prerelease: false
  name_template: "{{ .Tag }}"
